language: php

php:
  - 5.3
  - 5.4

before_script: 
  - COMPOSER=./tests/jackalope-testing-composer.json composer install

script: phpunit -c tests/phpunit.xml.dist

notifications:
  irc: "irc.freenode.org#jackalope"
