language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

before_script:
  # FIXME: remove require on jackalope/jackalope-transport
  # temporary fix until https://github.com/composer/composer/issues/2038 is implemented
  - sed '/jackalope\/jackalope-transport/d' composer.json >> tmp; mv tmp composer.json
  - composer update --prefer-source

script: phpunit

notifications:
  irc: "irc.freenode.org#jackalope"
